// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sobee.Domain.Data;

#nullable disable

namespace Sobee.Domain.Migrations.Sobee
{
    [DbContext(typeof(SobeecoredbContext))]
    [Migration("20260109212745_StockAsInt")]
    partial class StockAsInt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Sobee.Domain.Entities.Cart.GuestSession", b =>
                {
                    b.Property<string>("SessionId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("session_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("expires_at_utc");

                    b.Property<DateTime>("LastSeenAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_seen_at_utc");

                    b.Property<string>("Secret")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("secret");

                    b.HasKey("SessionId")
                        .HasName("GuestSessions_PK");

                    b.ToTable("GuestSessions", (string)null);
                });

            modelBuilder.Entity("Sobee.Domain.Entities.Cart.TcartItem", b =>
                {
                    b.Property<int>("IntCartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("intCartItemID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IntCartItemId"));

                    b.Property<DateTime?>("DtmDateAdded")
                        .HasColumnType("datetime")
                        .HasColumnName("dtmDateAdded");

                    b.Property<int?>("IntProductId")
                        .HasColumnType("int")
                        .HasColumnName("intProductID");

                    b.Property<int?>("IntQuantity")
                        .HasColumnType("int")
                        .HasColumnName("intQuantity");

                    b.Property<int?>("IntShoppingCartId")
                        .HasColumnType("int")
                        .HasColumnName("intShoppingCartID");

                    b.HasKey("IntCartItemId")
                        .HasName("TCartItems_PK");

                    b.HasIndex("IntProductId");

                    b.HasIndex("IntShoppingCartId");

                    b.ToTable("TCartItems", (string)null);
                });

            modelBuilder.Entity("Sobee.Domain.Entities.Cart.TshoppingCart", b =>
                {
                    b.Property<int>("IntShoppingCartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("intShoppingCartID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IntShoppingCartId"));

                    b.Property<DateTime?>("DtmDateCreated")
                        .HasColumnType("datetime")
                        .HasColumnName("dtmDateCreated");

                    b.Property<DateTime?>("DtmDateLastUpdated")
                        .HasColumnType("datetime")
                        .HasColumnName("dtmDateLastUpdated");

                    b.Property<string>("SessionId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("session_id");

                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("user_id");

                    b.HasKey("IntShoppingCartId")
                        .HasName("TShoppingCarts_PK");

                    b.ToTable("TShoppingCarts", (string)null);
                });

            modelBuilder.Entity("Sobee.Domain.Entities.Orders.Torder", b =>
                {
                    b.Property<int>("IntOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("intOrderID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IntOrderId"));

                    b.Property<decimal?>("DecTotalAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("decTotalAmount");

                    b.Property<DateTime?>("DtmOrderDate")
                        .HasColumnType("datetime")
                        .HasColumnName("dtmOrderDate");

                    b.Property<int?>("IntPaymentMethodId")
                        .HasColumnType("int")
                        .HasColumnName("intPaymentMethodID");

                    b.Property<int?>("IntShippingStatusId")
                        .HasColumnType("int")
                        .HasColumnName("intShippingStatusID");

                    b.Property<string>("SessionId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("session_id");

                    b.Property<string>("StrOrderStatus")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("strOrderStatus");

                    b.Property<string>("StrShippingAddress")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("strShippingAddress");

                    b.Property<string>("StrTrackingNumber")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("strTrackingNumber");

                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("user_id");

                    b.HasKey("IntOrderId")
                        .HasName("TOrders_PK");

                    b.HasIndex("IntPaymentMethodId");

                    b.HasIndex("IntShippingStatusId");

                    b.ToTable("TOrders", (string)null);
                });

            modelBuilder.Entity("Sobee.Domain.Entities.Orders.TorderItem", b =>
                {
                    b.Property<int>("IntOrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("intOrderItemID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IntOrderItemId"));

                    b.Property<int?>("IntOrderId")
                        .HasColumnType("int")
                        .HasColumnName("intOrderID");

                    b.Property<int?>("IntProductId")
                        .HasColumnType("int")
                        .HasColumnName("intProductID");

                    b.Property<int?>("IntQuantity")
                        .HasColumnType("int")
                        .HasColumnName("intQuantity");

                    b.Property<decimal?>("MonPricePerUnit")
                        .HasColumnType("money")
                        .HasColumnName("monPricePerUnit");

                    b.HasKey("IntOrderItemId")
                        .HasName("TOrderItems_PK");

                    b.HasIndex("IntOrderId");

                    b.HasIndex("IntProductId");

                    b.ToTable("TOrderItems", (string)null);
                });

            modelBuilder.Entity("Sobee.Domain.Entities.Orders.TordersProduct", b =>
                {
                    b.Property<int>("IntOrdersProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("intOrdersProductID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IntOrdersProductId"));

                    b.Property<int>("IntProductId")
                        .HasColumnType("int")
                        .HasColumnName("intProductID");

                    b.Property<string>("StrOrdersProduct")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("strOrdersProduct");

                    b.HasKey("IntOrdersProductId")
                        .HasName("TOrdersProducts_PK");

                    b.ToTable("TOrdersProducts", (string)null);
                });

            modelBuilder.Entity("Sobee.Domain.Entities.Orders.TshippingMethod", b =>
                {
                    b.Property<int>("IntShippingMethodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("intShippingMethodID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IntShippingMethodId"));

                    b.Property<DateTime>("DtmEstimatedDelivery")
                        .HasColumnType("datetime")
                        .HasColumnName("dtmEstimatedDelivery");

                    b.Property<string>("StrBillingAddress")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("strBillingAddress");

                    b.Property<string>("StrCost")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("strCost");

                    b.Property<string>("StrShippingName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("strShippingName");

                    b.HasKey("IntShippingMethodId")
                        .HasName("TShippingMethods_PK");

                    b.ToTable("TShippingMethods", (string)null);
                });

            modelBuilder.Entity("Sobee.Domain.Entities.Orders.TshippingStatus", b =>
                {
                    b.Property<int>("IntShippingStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("intShippingStatusID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IntShippingStatusId"));

                    b.Property<string>("StrShippingStatus")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("strShippingStatus");

                    b.HasKey("IntShippingStatusId")
                        .HasName("TShippingStatus_PK");

                    b.ToTable("TShippingStatus", (string)null);
                });

            modelBuilder.Entity("Sobee.Domain.Entities.Payments.Tpayment", b =>
                {
                    b.Property<int>("IntPaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("intPaymentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IntPaymentId"));

                    b.Property<int?>("IntPaymentMethod")
                        .HasColumnType("int")
                        .HasColumnName("intPaymentMethod");

                    b.Property<int?>("IntPaymentMethodId")
                        .HasColumnType("int")
                        .HasColumnName("intPaymentMethodID");

                    b.Property<string>("StrBillingAddress")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("strBillingAddress");

                    b.HasKey("IntPaymentId")
                        .HasName("TPayments_PK");

                    b.HasIndex("IntPaymentMethodId");

                    b.ToTable("TPayments", (string)null);
                });

            modelBuilder.Entity("Sobee.Domain.Entities.Payments.TpaymentMethod", b =>
                {
                    b.Property<int>("IntPaymentMethodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("intPaymentMethodID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IntPaymentMethodId"));

                    b.Property<string>("StrBillingAddress")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("strBillingAddress");

                    b.Property<string>("StrCreditCardDetails")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("strCreditCardDetails");

                    b.Property<string>("StrDescription")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("strDescription");

                    b.HasKey("IntPaymentMethodId")
                        .HasName("TPaymentMethods_PK");

                    b.ToTable("TPaymentMethods", (string)null);
                });

            modelBuilder.Entity("Sobee.Domain.Entities.Payments.TtransactionType", b =>
                {
                    b.Property<int>("IntTransactionTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("intTransactionTypeID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IntTransactionTypeId"));

                    b.Property<string>("StrTransactionType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("strTransactionType");

                    b.HasKey("IntTransactionTypeId")
                        .HasName("TTransactionTypes_PK");

                    b.ToTable("TTransactionTypes", (string)null);
                });

            modelBuilder.Entity("Sobee.Domain.Entities.Products.TdrinkCategory", b =>
                {
                    b.Property<int>("IntDrinkCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("intDrinkCategoryID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IntDrinkCategoryId"));

                    b.Property<string>("StrDescription")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("strDescription");

                    b.Property<string>("StrName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("strName");

                    b.HasKey("IntDrinkCategoryId")
                        .HasName("TDrinkCategories_PK");

                    b.ToTable("TDrinkCategories", (string)null);
                });

            modelBuilder.Entity("Sobee.Domain.Entities.Products.Tflavor", b =>
                {
                    b.Property<int>("IntFlavorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("intFlavorID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IntFlavorId"));

                    b.Property<string>("StrFlavor")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("strFlavor");

                    b.HasKey("IntFlavorId")
                        .HasName("TFlavors_PK");

                    b.ToTable("TFlavors", (string)null);
                });

            modelBuilder.Entity("Sobee.Domain.Entities.Products.Tingredient", b =>
                {
                    b.Property<int>("IntIngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("intIngredientID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IntIngredientId"));

                    b.Property<string>("StrIngredient")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("strIngredient");

                    b.HasKey("IntIngredientId")
                        .HasName("TIngredients_PK");

                    b.ToTable("TIngredients", (string)null);
                });

            modelBuilder.Entity("Sobee.Domain.Entities.Products.Tproduct", b =>
                {
                    b.Property<int>("IntProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("intProductID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IntProductId"));

                    b.Property<decimal>("DecPrice")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("decPrice");

                    b.Property<int>("IntStockAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("IntStockAmount");

                    b.Property<string>("StrName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("strName");

                    b.Property<string>("strDescription")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("strDescription");

                    b.HasKey("IntProductId")
                        .HasName("TProducts_PK");

                    b.ToTable("TProducts", (string)null);
                });

            modelBuilder.Entity("Sobee.Domain.Entities.Products.TproductImage", b =>
                {
                    b.Property<int>("IntProductImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("intProductImageID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IntProductImageId"));

                    b.Property<string>("StrProductImageUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("strProductImageURL");

                    b.HasKey("IntProductImageId")
                        .HasName("TProductImages_PK");

                    b.ToTable("TProductImages", (string)null);
                });

            modelBuilder.Entity("Sobee.Domain.Entities.Promotions.TpromoCodeUsageHistory", b =>
                {
                    b.Property<int>("IntUsageHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("intUsageHistoryID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IntUsageHistoryId"));

                    b.Property<int>("IntShoppingCartId")
                        .HasColumnType("int")
                        .HasColumnName("intShoppingCartID");

                    b.Property<string>("PromoCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("UsedDateTime")
                        .HasColumnType("datetime");

                    b.HasKey("IntUsageHistoryId")
                        .HasName("TPromoCodeUsageHistory_PK");

                    b.HasIndex("IntShoppingCartId");

                    b.ToTable("TPromoCodeUsageHistory", (string)null);
                });

            modelBuilder.Entity("Sobee.Domain.Entities.Promotions.Tpromotion", b =>
                {
                    b.Property<int?>("IntPromotionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("intPromotionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("IntPromotionId"));

                    b.Property<decimal>("DecDiscountPercentage")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("decDiscountPercentage");

                    b.Property<DateTime>("DtmExpirationDate")
                        .HasColumnType("datetime")
                        .HasColumnName("dtmExpirationDate");

                    b.Property<string>("StrDiscountPercentage")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("strDiscountPercentage");

                    b.Property<string>("StrPromoCode")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("strPromoCode");

                    b.HasKey("IntPromotionId")
                        .HasName("TPromotions_PK");

                    b.ToTable("TPromotions", (string)null);
                });

            modelBuilder.Entity("Sobee.Domain.Entities.Reviews.TReviewReplies", b =>
                {
                    b.Property<int>("IntReviewReplyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("intReviewReplyID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IntReviewReplyID"));

                    b.Property<int>("IntReviewId")
                        .HasColumnType("int")
                        .HasColumnName("review_id");

                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("user_id");

                    b.Property<string>("content")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("IntReviewReplyID")
                        .HasName("TReviewReplies_PK");

                    b.HasIndex("IntReviewId");

                    b.ToTable("TReviewReplies", (string)null);
                });

            modelBuilder.Entity("Sobee.Domain.Entities.Reviews.Tfavorite", b =>
                {
                    b.Property<int>("IntFavoriteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("intFavoriteID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IntFavoriteId"));

                    b.Property<DateTime>("DtmDateAdded")
                        .HasColumnType("datetime")
                        .HasColumnName("dtmDateAdded");

                    b.Property<int>("IntProductId")
                        .HasColumnType("int")
                        .HasColumnName("intProductID");

                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("user_id");

                    b.HasKey("IntFavoriteId")
                        .HasName("TFavorites_PK");

                    b.HasIndex("IntProductId");

                    b.ToTable("TFavorites", (string)null);
                });

            modelBuilder.Entity("Sobee.Domain.Entities.Reviews.Treview", b =>
                {
                    b.Property<int>("IntReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("intReviewID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IntReviewId"));

                    b.Property<DateTime>("DtmReviewDate")
                        .HasColumnType("datetime")
                        .HasColumnName("dtmReviewDate");

                    b.Property<int>("IntProductId")
                        .HasColumnType("int")
                        .HasColumnName("intProductID");

                    b.Property<int>("IntRating")
                        .HasColumnType("int")
                        .HasColumnName("intRating");

                    b.Property<string>("SessionId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("session_id");

                    b.Property<string>("StrReviewText")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("strReviewText");

                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("user_id");

                    b.HasKey("IntReviewId")
                        .HasName("TReviews_PK");

                    b.HasIndex("IntProductId");

                    b.ToTable("TReviews", (string)null);
                });

            modelBuilder.Entity("Sobee.Domain.Entities.Cart.TcartItem", b =>
                {
                    b.HasOne("Sobee.Domain.Entities.Products.Tproduct", "IntProduct")
                        .WithMany("TcartItems")
                        .HasForeignKey("IntProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("TCartItems_TProducts_FK");

                    b.HasOne("Sobee.Domain.Entities.Cart.TshoppingCart", "IntShoppingCart")
                        .WithMany("TcartItems")
                        .HasForeignKey("IntShoppingCartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("TCartItems_TShoppingCarts_FK");

                    b.Navigation("IntProduct");

                    b.Navigation("IntShoppingCart");
                });

            modelBuilder.Entity("Sobee.Domain.Entities.Orders.Torder", b =>
                {
                    b.HasOne("Sobee.Domain.Entities.Payments.TpaymentMethod", "IntPaymentMethod")
                        .WithMany("Torders")
                        .HasForeignKey("IntPaymentMethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("TOrders_TPaymentMethods_FK");

                    b.HasOne("Sobee.Domain.Entities.Orders.TshippingStatus", "IntShippingStatus")
                        .WithMany("Torders")
                        .HasForeignKey("IntShippingStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("TOrders_TShippingStatus_FK");

                    b.Navigation("IntPaymentMethod");

                    b.Navigation("IntShippingStatus");
                });

            modelBuilder.Entity("Sobee.Domain.Entities.Orders.TorderItem", b =>
                {
                    b.HasOne("Sobee.Domain.Entities.Orders.Torder", "IntOrder")
                        .WithMany("TorderItems")
                        .HasForeignKey("IntOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("TOrderItems_TOrders_FK");

                    b.HasOne("Sobee.Domain.Entities.Products.Tproduct", "IntProduct")
                        .WithMany("TorderItems")
                        .HasForeignKey("IntProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("TOrderItems_TProducts_FK");

                    b.Navigation("IntOrder");

                    b.Navigation("IntProduct");
                });

            modelBuilder.Entity("Sobee.Domain.Entities.Payments.Tpayment", b =>
                {
                    b.HasOne("Sobee.Domain.Entities.Payments.TpaymentMethod", "IntPaymentMethodNavigation")
                        .WithMany("Tpayments")
                        .HasForeignKey("IntPaymentMethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("TPayments_TPaymentMethods_FK");

                    b.Navigation("IntPaymentMethodNavigation");
                });

            modelBuilder.Entity("Sobee.Domain.Entities.Promotions.TpromoCodeUsageHistory", b =>
                {
                    b.HasOne("Sobee.Domain.Entities.Cart.TshoppingCart", "IntShoppingCart")
                        .WithMany("TpromoCodeUsageHistories")
                        .HasForeignKey("IntShoppingCartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("TPromoCodeUsageHistory_TShoppingCarts_FK");

                    b.Navigation("IntShoppingCart");
                });

            modelBuilder.Entity("Sobee.Domain.Entities.Reviews.TReviewReplies", b =>
                {
                    b.HasOne("Sobee.Domain.Entities.Reviews.Treview", "Treview")
                        .WithMany("TReviewReplies")
                        .HasForeignKey("IntReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ReviewReplies_Reviews");

                    b.Navigation("Treview");
                });

            modelBuilder.Entity("Sobee.Domain.Entities.Reviews.Tfavorite", b =>
                {
                    b.HasOne("Sobee.Domain.Entities.Products.Tproduct", "IntProduct")
                        .WithMany("Tfavorites")
                        .HasForeignKey("IntProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("TFavorites_TProducts_FK");

                    b.Navigation("IntProduct");
                });

            modelBuilder.Entity("Sobee.Domain.Entities.Reviews.Treview", b =>
                {
                    b.HasOne("Sobee.Domain.Entities.Products.Tproduct", "IntProduct")
                        .WithMany("Treviews")
                        .HasForeignKey("IntProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("TReviews_TProducts_FK");

                    b.Navigation("IntProduct");
                });

            modelBuilder.Entity("Sobee.Domain.Entities.Cart.TshoppingCart", b =>
                {
                    b.Navigation("TcartItems");

                    b.Navigation("TpromoCodeUsageHistories");
                });

            modelBuilder.Entity("Sobee.Domain.Entities.Orders.Torder", b =>
                {
                    b.Navigation("TorderItems");
                });

            modelBuilder.Entity("Sobee.Domain.Entities.Orders.TshippingStatus", b =>
                {
                    b.Navigation("Torders");
                });

            modelBuilder.Entity("Sobee.Domain.Entities.Payments.TpaymentMethod", b =>
                {
                    b.Navigation("Torders");

                    b.Navigation("Tpayments");
                });

            modelBuilder.Entity("Sobee.Domain.Entities.Products.Tproduct", b =>
                {
                    b.Navigation("TcartItems");

                    b.Navigation("Tfavorites");

                    b.Navigation("TorderItems");

                    b.Navigation("Treviews");
                });

            modelBuilder.Entity("Sobee.Domain.Entities.Reviews.Treview", b =>
                {
                    b.Navigation("TReviewReplies");
                });
#pragma warning restore 612, 618
        }
    }
}
